Update webinfo

diff --git a/webinfo b/webinfo
--- a/webinfo
+++ b/webinfo
@@ -1,11 +1,11 @@
 #!/data/data/com.termux/files/usr/bin/bash
 clear
-command -v toilet > /dev/null 2>&1 || { echo >&2 $'\e[32;1m'"toilet not found !, Installing... toilet"$'\e[37m'; pkg install toilet -y 1; }
-command -v figlet > /dev/null 2>&1 || { echo >&2 $'\e[32;1m'"figlet not found!, Installing... figlet"$'\e[37m'; pkg install figlet -y 1; }
-command -v whois > /dev/null 2>&1 || { echo >&2 $'\e[32;1m'"whois not found!, Installing... whois"$'\e[37m'; pkg install whois -y 1; }
-command -v traceroute > /dev/null 2>&1 || { echo >&2 $'\e[32;1m'"traceroute not found!, Installing.... traceroute"$'\e[37m'; pkg install traceroute -y 1; }
-command -v nmap > /dev/null 2>&1 || { echo >&2 $'\e[32;1m'"nmap not found!, Installing... nmap"$'\e[37m'; pkg install nmap -y 1; }
-command -v host > /dev/null 2>&1 || { echo >&2 $'\e[32;1m'"host not found!, Installing... dnsutils"$'\e[37m'; pkg install dnsutils -y 1; }
+command -v toilet > /dev/null 2>&1 || { echo >&2 "toilet not found !, Installing... toilet"; pkg install toilet -y 1; }
+command -v figlet > /dev/null 2>&1 || { echo >&2 "figlet not found!, Installing... figlet"; pkg install figlet -y 1; }
+command -v whois > /dev/null 2>&1 || { echo >&2 "whois not found!, Installing... whois"; pkg install whois -y 1; }
+command -v traceroute > /dev/null 2>&1 || { echo >&2 "traceroute not found!, Installing.... traceroute"; pkg install traceroute -y 1; }
+command -v nmap > /dev/null 2>&1 || { echo >&2 "nmap not found!, Installing... nmap"; pkg install nmap -y 1; }
+command -v host > /dev/null 2>&1 || { echo >&2 "host not found!, Installing... dnsutils"; pkg install dnsutils -y 1; }
 clear
 echo $'\33[32;1m'""
 figlet -f smblock "                     Webinfo"
